#!/usr/bin/with-contenv sh

USER=serf
BIN=/usr/sbin/serf
CONFIG=/etc/serf.d
BIND=`getent hosts $HOSTNAME | awk '{print $1}'`

exec s6-setuidgid $USER $BIN agent -config-dir $CONFIG -bind $BIND -retry-interval 15s;
