#!/usr/bin/with-contenv sh

/usr/bin/ssh-keygen -A

exec /usr/sbin/sshd -D -o UseDNS=no                  \
                       -o UsePAM=no                  \
                       -o PasswordAuthentication=yes \
                       -o UsePrivilegeSeparation=no  \
                       -o PidFile=/tmp/sshd.pid;
