#!/usr/bin/with-contenv sh

USER=serf
BIN=/opt/serf/sbin/serf
LOG=/opt/serf/log/agent.log
CONFIG=/opt/serf/config/serf_agent.json

exec s6-setuidgid $USER $BIN agent -config-file $CONFIG >> $LOG 2>&1;
